#
# Sera - OnePage Jekyll Template
# Configuration File
#

# Information for compile
exclude: ["node_modules", "gulpfile.js", "package.json", "Gemfile", "README.md", "resources"]

#
# If your website is placed in a separate folder on your server please modify
# this with your folder name, by default is empty.
# Example: Sera Demo is hosted on projects.gleesik.ro/sera-onepage
# If I compile Sera Template and I put in /sera-onepage without modifing baseurl
# than scripts can't be loaded corectly.
# For this example my site url is: projects.gleesik.ro (This can be just www.example.com)
# My folder for Demo Website is: /sera-onepage so baseurl: /sera-onepage
#
baseurl:

# the base hostname & protocol for your site
url: "http://localhost:3000"

####################################
######   Optional Features    ######
####################################
smooth-scroll: false

####################################
###########   Plugins    ###########
####################################
plugins:
  - jekyll-archives # Sorry, not GitHub pages friendly!

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: Diode - The IoT Network
# Website language
lang: en-US
# Header Title
header-title: <strong>The Future of IoT</strong>
# Header Tagline
headter-tagline: Welcome to

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: Watch Video
  url: https://youtu.be/uKfKtXYLG78

# Secondary Buttons
header-secondary-button:
  title: Whitepaper
  url: whitepaper.pdf

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: your_email@example.com

# Offer Banner Link
# Default link is a link to all Sera OnePage products
banner-link: /signup

####################################
######  Global Navigation     ######
####################################

navigation:
- title: Home
  link: /#home
- title: About
  link: /#about
- title: Features
  link: /#features
- title: News+Events
  link: /#news_events
- title: Team
  link: /#team
- title: Contact
  link: /#contact
- title: Blog
  link: /blog/


####################################
######  Global Social Links   ######
####################################
# youtube: '#'
# pinterest: '#'
# facebook: '#'
twitter: 'https://twitter.com/diode_chain'
telegram: 'https://t.me/DiodeChain'
# google-plus: '#'
# vimeo: '#'

#########################
######   Widgets   ######
#########################

#
# About Blog Author Widget
#
about-widget:
  author-avatar: avatar-02.jpg
  author-name: John Doe
  author-tagline: Blog Author
  author-info: Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies.
  author-social-links:
    youtube: '#'
    pinterest: '#'
    facebook: '#'
    twitter: '#'
    google-plus: '#'

# Google Map JS api
# This is my api for this template
key-api: AIzaSyDbnxVZQannH0GF4gtnnBFPiP9ofm2WqGs
map-text: Sera Google Map
map-text-location: Bucharest, Romania
map-lat: 44.4267674
map-lng: 26.102538399999958

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
mailchimp:
  user-id: REPLACEME
  list-id: REPLACEME

####
#
# Hi you now use Sera - OnePage Jekyll Template created by Gleesik™
#
# Below are each section from the website in order from top to bottom
# @TODO Edit each sections with your real information and each section from Sera will autocomplete with your information
#
####

#####################################
#############   About   #############
#####################################
about-title: Diode IoT Network
about-description: >-
  The Diode IoT Network is a new type of transport layer specifically designed for IoT
  devices. Diode is the first network to implement unforgable network-device authentication
  based on blockchain technology. Man-In-The middle attacks become impossible and dependencies 
  on third parties to entrust security are removed. The network has higher security than PKI with
  much lower overhead and maintenance needs. Truly autonomous.
  Diode allows developers to build new IoT applications on top of it's network or migrate existing
  workloads for the higher security and lower operating costs.
  


#####################################
#############  Features  ############
#####################################
features-title: What can Diode do for IoT?
features-description:

#
# Features
#
features:

# Feature
- title: Secure Connectivity
  description: >-
    Merkle proof secured identity data in the blockchain not only make for tamper proof
    data, but also allow proofing recentness. Whether it's credentials or software updates IoT
    devices not only can proof validity but also proof recentness. 
    Using encryption technology accross the network no third party can read or access your data.

  icon: pe-7s-shield

# Feature
- title: Lower Cost
  description: >-
    The Diode Network creates an IoT marketplace in which providers compete for your business,
    which leads to the lowest possible prices. The blockchain autonomously keeps the controls
    tight and ensure correct behaviour.

  icon: pe-7s-gift

# Feature
- title: Streaming Network
  description: >-
    Whether it is video data from a home camera to an end user or broadcasting messages to thousands of 
    endpoints the Diode Network is a native IoT network providing streaming and storage services for all 
    connected devices.

  icon: pe-7s-shuffle


#####################################
############# Our Blog ##############
#####################################
blog-title: News + Events
blog-description: >-
  As we're working on rolling out the next evolutionary steps of the Diode network we will be 
  posting updates regularly. Also keep track of our twitter account to get all the latest news.


#####################################
############### Team ################
#####################################
team-title: Meet Our Team
team-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.

#
# Team Members
#
team:

# Team Member
- name: Dominic Letz
  tagline: Chief Technology Officer
  avatar: dominic-letz.jpg

  # Social Links
  # youtube: '#'
  # pinterest: '#'
  # facebook: '#'
  # twitter: '#'
  # google-plus: '#'
  # vimeo: '#'

# Team Member
- name: Greg Belcher
  tagline: VP Business Development
  avatar: greg-belcher.jpg

  # Social Links
  # youtube: '#'
  # pinterest: '#'
  # facebook: '#'
  # twitter: '#'
  # google-plus: '#'
  # vimeo: '#'

# Team Member
- name: Hans Rempel
  tagline: CEO
  avatar: hans-rempel.jpg

  # Social Links
  # youtube: '#'
  # pinterest: '#'
  # facebook: '#'
  # twitter: '#'
  # google-plus: '#'
  # vimeo: '#'

#####################################
############   Contact   ############
#####################################
contact-title: Say Hello
contact-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat.


#####################################
#############   Footer   ############
#####################################
footer-description: 
footer-copyright-text: DIODE
footer-copyright-url: https://diodechain.io/
footer-copyright-year: 2019



#####################################
##########  Core Features  ##########
#####################################
# core-title: Core Features
# core-description: Duis at odio vitae ex gravida volutpat. Nulla finibus aliquet diam ut eleifend. Mauris consequat interdum quam. Mauris dui sapien, efficitur et cursus id, molestie fringilla turpis aliquet diam ut eleifend.

# #
# # Core Features Left
# #
# core-features-left:

# # Feature
# - name: Creative
#   description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
#   icon: pe-7s-light

# # Feature
# - name: Minimalism
#   description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
#   icon: pe-7s-drop

# # Feature
# - name: Clean Coding
#   description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
#   icon: pe-7s-coffee

# # Feature
# - name: Friendly
#   description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
#   icon: pe-7s-smile

# #
# # Core Features Right
# #
# core-features-right:

# # Feature
# - name: Branding
#   description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
#   icon: pe-7s-wine

# # Feature
# - name: Web Design
#   description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
#   icon: pe-7s-monitor

# # Feature
# - name: Graphic Design
#   description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
#   icon: pe-7s-crop

# # Feature
# - name: Photography
#   description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
#   icon: pe-7s-camera


# #####################################
# ########### Testimonials ############
# #####################################
# testimonials-title: Testimonials
# testimonials-description: Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi.

# #
# # Testimonials
# #
# testimonials:

# # Client
# - name: Johnatan Doe
#   url: http://themeforest.net
#   url-text: ThemeForest.net
#   avatar: avatar-01.jpg
#   cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
#   logo-img: themeforest.png

# # Client
# - name: Adam Smith
#   url: http://codecanyon.net
#   url-text: CodeCanyon.net
#   avatar: avatar-02.jpg
#   cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
#   logo-img: codecanyon.png

# # Client
# - name: Irene Warner
#   url: http://videohive.net
#   url-text: VideoHive.net
#   avatar: avatar-03.jpg
#   cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
#   logo-img: videohive.png

# # Client
# - name: Richard Ryan
#   url: http://audiojungle.net
#   url-text: AudioJungle.net
#   avatar: avatar-04.jpg
#   cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
#   logo-img: audiojungle.png

#####################################
########## Pricing Tables ###########
#####################################
# pricing-title: Pricing Tables
# pricing-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.

# #
# # Plan Personal
# #
# plan-personal-price: $99
# plan-personal-offer-1-title: 01 PSD Pack
# plan-personal-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
# plan-personal-offer-2-title: 100 Support Tickets
# plan-personal-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
# plan-personal-url: '#'

# #
# # Plan Business
# #
# plan-business-price: $499
# plan-business-offer-1-title: 05 PSD Pack
# plan-business-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
# plan-business-offer-2-title: 1000 Support Tickets
# plan-business-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
# plan-business-url: '#'

# #
# # Plan Ultimate
# #
# plan-ultimate-price: $999
# plan-ultimate-offer-1-title: 10 PSD Pack
# plan-ultimate-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
# plan-ultimate-offer-2-title: Support Unlimited
# plan-ultimate-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
# plan-ultimate-url: '#'

#########################
######   Widgets   ######
#########################

# #
# # About Blog Author Widget
# #
# about-widget:
#   author-avatar: avatar-02.jpg
#   author-name: John Doe
#   author-tagline: Blog Author
#   author-info: Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies.
#   author-social-links:
#     youtube: '#'
#     pinterest: '#'
#     facebook: '#'
#     twitter: '#'
#     google-plus: '#'

# # Google Map JS api
# # This is my api for this template
# key-api: AIzaSyDbnxVZQannH0GF4gtnnBFPiP9ofm2WqGs
# map-text: Sera Google Map
# map-text-location: Bucharest, Romania
# map-lat: 44.4267674
# map-lng: 26.102538399999958

#####################################
############  Portfolio  ############
#####################################
#~ portfolio-title: Portfolio
#~ portfolio-description: Maecenas tempus nec mi et placerat. Duis at odio vitae ex gravida volutpat. Nulla finibus aliquet diam ut eleifend. Mauris consequat interdum quam. Mauris dui sapien, efficitur et cursus id, molestie fringilla turpis.

#~ #
#~ # Portfolio Grid
#~ #
#~ portfolio-categories: [Websites, Logo, Graphic Design, Development, Video, Photography]
#~ portfolio:

#~ # Portfolio Item
#~ - title: S<span class="thin">era</span> Style
  #~ categories: [Websites, Graphic Design]
  #~ image: img-01.jpg
  #~ url: '#'

#~ # Portfolio Item
#~ - title: S<span class="thin">era</span> Style
  #~ categories: [Graphic Design, Logo, Websites]
  #~ image: img-02.jpg
  #~ url: '#'

#~ # Portfolio Item
#~ - title: S<span class="thin">era</span> Style
  #~ categories: [Graphic Design, Logo, Photography]
  #~ image: img-03.jpg
  #~ url: '#'

#~ # Portfolio Item
#~ - title: S<span class="thin">era</span> Style
  #~ categories: [Websites, Video, Photography]
  #~ image: img-04.jpg
  #~ url: '#'

#~ # Portfolio Item
#~ - title: S<span class="thin">era</span> Style
  #~ categories: [Development, Logo]
  #~ image: img-05.jpg
  #~ url: '#'

#~ # Portfolio Item
#~ - title: S<span class="thin">era</span> Style
  #~ categories: [Development, Video]
  #~ image: img-06.jpg
  #~ url: '#'

#~ # Portfolio Item
#~ - title: S<span class="thin">era</span> Style
  #~ categories: [Websites, Graphic Design]
  #~ image: img-07.jpg
  #~ url: '#'

#~ # Portfolio Item
#~ - title: S<span class="thin">era</span> Style
  #~ categories: [Websites , Video]
  #~ image: img-08.jpg
  #~ url: '#'

#~ # Portfolio Item
#~ - title: S<span class="thin">era</span> Style
  #~ categories: [Photography, Logo]
  #~ image: img-09.jpg
  #~ url: '#'
