# Information for compile
exclude: ["node_modules", "gulpfile.js", "package.json", "Gemfile", "README.md", "resources", "run"]

baseurl:

plugins:
  - jekyll-redirect-from

# the base hostname & protocol for your site
url: "https://diode.io"

####################################
######   Optional Features    ######
####################################
smooth-scroll: false

####################################
#############   Tags    ############
####################################

tagurl: '/blog/tags.html#'

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: Diode&#8480; - The IoT Blockchain Network that actually works on small devices
# Meta description
description: The First Super Light Client and Blockchain Network for IoT, ARM, ESP32, Arduino, RaspberryPI and other embedded MCU
# Website language
lang: en-US
# Header Title
header-title: <strong>Make it rock solid</strong>
# Header Tagline
header-tagline: IoT security is broken

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: Watch the Video
  url: https://player.vimeo.com/video/318384993?autoplay=1

# Secondary Buttons
header-secondary-button:
  title: BlockQuick Paper
  url: https://eprint.iacr.org/2019/579.pdf

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: your_email@example.com

# Offer Banner Link
# Default link is a link to all Sera OnePage products
banner-link: /signup

####################################
######  Global Navigation     ######
####################################

navigation:
- title: Home
  link: /#home
- title: About
  link: /#about
- title: Features
  link: /#features
- title: News+Events
  link: /#news_events
- title: Team
  link: /#team
# - title: Contact
#   link: /#contact
- title: Blog
  link: /blog/
- title: <i class="fi flaticon-telegram"></i>
  link: https://t.me/diode_chain
  target: _blank
- title: <i class="fi flaticon-twitter"></i>
  link: https://twitter.com/diode_chain
  target: _blank


####################################
######  Global Social Links   ######
####################################
youtube: 'https://www.youtube.com/channel/UC3b5voADiipUmq1Q-vtPKsA'
# pinterest: '#'
# facebook: '#'
twitter: 'https://twitter.com/diode_chain'
twitter_username: 'diode_chain'
telegram: 'https://t.me/diode_chain'
# google-plus: '#'
# vimeo: '#'

#########################
######   Widgets   ######
#########################

# Google Map JS api
# This is my api for this template
key-api: AIzaSyDbnxVZQannH0GF4gtnnBFPiP9ofm2WqGs
map-text: Sera Google Map
map-text-location: Bucharest, Romania
map-lat: 44.4267674
map-lng: 26.102538399999958

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
mailchimp:
  user-id: REPLACEME
  list-id: REPLACEME

####
#
# Hi you now use Sera - OnePage Jekyll Template created by Gleesik™
#
# Below are each section from the website in order from top to bottom
# @TODO Edit each sections with your real information and each section from Sera will autocomplete with your information
#
####

#####################################
#############   About   #############
#####################################
about-title: Diode<sup>sm</sup> IIoT/IoT Network
about-description: >-
  PKI the system that protects web traffic since 30 years is broken for IoT. The governance structures 
  have failed, broken implementations and misuse are spread far beyond repair and fraud is done through it's 
  weaknesses every day. Our Diode Chain&trade; software creates a new network designed for smart
  devices. The Diode Network is the first to implement unforgable proof-of-time and network-device authentication
  based on blockchain technology. 
  Man-In-The middle attacks become impossible and dependencies 
  on third parties to entrust security are removed. The network has higher security than PKI with
  much lower overhead and maintenance needs. Truly autonomous.
  Diode allows developers to build new IoT applications on top of it's network or migrate existing
  workloads for the higher security and lower operating costs.

#####################################
#############  Features  ############
#####################################
features-title: What can Diode do for IoT?
features-description:

#
# Features
#
features:

# Feature
- title: Secure Connectivity
  description: >-
    The Diode Chain software uses unique blockchain authentication that allows devices to establish secure connectivity
    to the blockchain. From there, devices have full access to the data protected by the blockchain
    consensus. Traditional Man-In-The-Middle attacks through fake PKI certificates and DNS spoofing
    have no chance.

  icon: svgs/security.svg

# Feature
- title: Lower Cost
  description: >-
    The Diode Network creates an IoT resource marketplace in which providers compete for your business,
    which leads to the lowest possible prices. The blockchain autonomously keeps the controls
    tight and ensures correct behaviour.

  icon: svgs/lower_cost.svg

# Feature
- title: Streaming Network
  description: >-
    Whether it is video data from a home camera to an end user or broadcasting messages to thousands of 
    endpoints, the Diode Network is a native IoT network providing streaming and storage services for all 
    connected devices.

  icon: svgs/streaming.svg


#####################################
############   About us   ###########
#####################################
about-us-title: Diode<sup>sm</sup>
about-us-description: >-
  Diode is responsible for governance and issuance of Diode Tokens, governance and maintenance of the Diode Network, and growing the ecosystem surrounding both.  The Diode Network is formed by the producers and miners who run instances of the Diode Chain&trade; Software.  The Diode Chain Software’s development and configuration management is provided by Diode.  Users of the Diode Network must use Diode Tokens to be granted access to the Diode Network’s unique capabilities for secure IoT communications.  Diode manages the issuance (block rewards) and other tokenomics for Diode Tokens.
  
#####################################
####### Diode Chain Features  #######
#####################################
chain-features-title: What is the Diode Chain<sup>tm</sup> software?
chain-features-description:

  #
# Diode Chain Features
#
chain-features:

# Feature
- title: Edge Connector
  description: >-
    Designed for microchips Diode Chains edge connector software runs even on very constrained client 
    devices. Written in protable C and implemening Diodes BlockQuick&trade; algorithm this piece of
    sofware allos to connect real world microchips such as the TI CC3220, development boards such as
    Arduino Yun and Industrial Gateways securely to the IoT cloud. With 10x less memory than 
    competitive products it's delivering 1000x times higher security for endpoint devices.

  icon: svgs/security.svg

# Feature
- title: Efficient & Secure Mining
  description: >-
    The Diode Chain software bundles the StakeWork&trade; consensus algorithm, providing more than 3x
    better energy efficiency compared with BitCoin and Ethereum while providing effective protections
    against Proof-Of-Work attacks. The algorithm is bundled with both the edge connector and the
    mining node software providing providing reference implementations.  

  icon: svgs/streaming.svg

# Feature
- title: Mining Node Sofware
  description: >-
    The full nodes of the Diode network are Ethereum VM and Ethereum RPC compatible offering 
    developers access to the full set of the development tools of the Ethereum Ecosystem
    such as remix and solidity. The Diode Chain software bundle contains the full reference
    implementation allowing easy operation in datacanters and mining operations. 

  icon: svgs/lower_cost.svg


#####################################
############# Our Blog ##############
#####################################
blog-name: The Blockchain Journal
blog-title: News + Events
blog-description: >-
  As we're working on rolling out the next evolutionary steps of the Diode Network we will be 
  posting updates regularly. Also keep track of our twitter account to get all the latest news.


#####################################
############### Team ################
#####################################
team-title: Management Team
team-description: >-
  Our team consists of true IoT experts from both the business and the technology side. We're dedicated
  to a secure IoT future!

#####################################
#############   Footer   ############
#####################################
footer-description: 
footer-copyright-text: DIODE
footer-copyright-url: https://diode.io/
footer-copyright-year: 2019

#########################
######   Widgets   ######
#########################

collections:
  posts:
    output: true 
    permalink: /:categories/:title-:short_year:y_day/
  team:
    output: true 

defaults:
  - scope:
      path: ""
      type: team
    values:
      layout: postlist
      tagline: All Articles By
      type: team